FROM golang:1.16 as builder

RUN mkdir /app
# Set the Current Working Directory inside the container
WORKDIR /app

COPY . .

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download